// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.chanyu.projectl.protobuf;

public final class Abyss {
  private Abyss() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class BeginSecretPlaceFightRequestProto extends
      com.google.protobuf.GeneratedMessage {
    // Use BeginSecretPlaceFightRequestProto.newBuilder() to construct.
    private BeginSecretPlaceFightRequestProto() {}
    
    private static final BeginSecretPlaceFightRequestProto defaultInstance = new BeginSecretPlaceFightRequestProto();
    public static BeginSecretPlaceFightRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public BeginSecretPlaceFightRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chanyu.projectl.protobuf.Abyss.internal_static_chanyu_BeginSecretPlaceFightRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chanyu.projectl.protobuf.Abyss.internal_static_chanyu_BeginSecretPlaceFightRequestProto_fieldAccessorTable;
    }
    
    // required int32 currentFloor = 1;
    public static final int CURRENTFLOOR_FIELD_NUMBER = 1;
    private boolean hasCurrentFloor;
    private int currentFloor_ = 0;
    public boolean hasCurrentFloor() { return hasCurrentFloor; }
    public int getCurrentFloor() { return currentFloor_; }
    
    // required bool clearCD = 2;
    public static final int CLEARCD_FIELD_NUMBER = 2;
    private boolean hasClearCD;
    private boolean clearCD_ = false;
    public boolean hasClearCD() { return hasClearCD; }
    public boolean getClearCD() { return clearCD_; }
    
    public final boolean isInitialized() {
      if (!hasCurrentFloor) return false;
      if (!hasClearCD) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCurrentFloor()) {
        output.writeInt32(1, getCurrentFloor());
      }
      if (hasClearCD()) {
        output.writeBool(2, getClearCD());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCurrentFloor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCurrentFloor());
      }
      if (hasClearCD()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getClearCD());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto result;
      
      // Construct using com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto();
        return builder;
      }
      
      protected com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto.getDescriptor();
      }
      
      public com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto getDefaultInstanceForType() {
        return com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto) {
          return mergeFrom((com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto other) {
        if (other == com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto.getDefaultInstance()) return this;
        if (other.hasCurrentFloor()) {
          setCurrentFloor(other.getCurrentFloor());
        }
        if (other.hasClearCD()) {
          setClearCD(other.getClearCD());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCurrentFloor(input.readInt32());
              break;
            }
            case 16: {
              setClearCD(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required int32 currentFloor = 1;
      public boolean hasCurrentFloor() {
        return result.hasCurrentFloor();
      }
      public int getCurrentFloor() {
        return result.getCurrentFloor();
      }
      public Builder setCurrentFloor(int value) {
        result.hasCurrentFloor = true;
        result.currentFloor_ = value;
        return this;
      }
      public Builder clearCurrentFloor() {
        result.hasCurrentFloor = false;
        result.currentFloor_ = 0;
        return this;
      }
      
      // required bool clearCD = 2;
      public boolean hasClearCD() {
        return result.hasClearCD();
      }
      public boolean getClearCD() {
        return result.getClearCD();
      }
      public Builder setClearCD(boolean value) {
        result.hasClearCD = true;
        result.clearCD_ = value;
        return this;
      }
      public Builder clearClearCD() {
        result.hasClearCD = false;
        result.clearCD_ = false;
        return this;
      }
    }
    
    static {
      com.chanyu.projectl.protobuf.Abyss.getDescriptor();
    }
    
    static {
      com.chanyu.projectl.protobuf.Abyss.internalForceInit();
    }
  }
  
  public static final class BeginSecretPlaceFightResponseProto extends
      com.google.protobuf.GeneratedMessage {
    // Use BeginSecretPlaceFightResponseProto.newBuilder() to construct.
    private BeginSecretPlaceFightResponseProto() {}
    
    private static final BeginSecretPlaceFightResponseProto defaultInstance = new BeginSecretPlaceFightResponseProto();
    public static BeginSecretPlaceFightResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public BeginSecretPlaceFightResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chanyu.projectl.protobuf.Abyss.internal_static_chanyu_BeginSecretPlaceFightResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chanyu.projectl.protobuf.Abyss.internal_static_chanyu_BeginSecretPlaceFightResponseProto_fieldAccessorTable;
    }
    
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean hasResult;
    private int result_ = 0;
    public boolean hasResult() { return hasResult; }
    public int getResult() { return result_; }
    
    // optional int32 currentFloor = 2;
    public static final int CURRENTFLOOR_FIELD_NUMBER = 2;
    private boolean hasCurrentFloor;
    private int currentFloor_ = 0;
    public boolean hasCurrentFloor() { return hasCurrentFloor; }
    public int getCurrentFloor() { return currentFloor_; }
    
    public final boolean isInitialized() {
      if (!hasResult) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasResult()) {
        output.writeInt32(1, getResult());
      }
      if (hasCurrentFloor()) {
        output.writeInt32(2, getCurrentFloor());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getResult());
      }
      if (hasCurrentFloor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getCurrentFloor());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto result;
      
      // Construct using com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto();
        return builder;
      }
      
      protected com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto.getDescriptor();
      }
      
      public com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto getDefaultInstanceForType() {
        return com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto) {
          return mergeFrom((com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto other) {
        if (other == com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasCurrentFloor()) {
          setCurrentFloor(other.getCurrentFloor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setResult(input.readInt32());
              break;
            }
            case 16: {
              setCurrentFloor(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 result = 1;
      public boolean hasResult() {
        return result.hasResult();
      }
      public int getResult() {
        return result.getResult();
      }
      public Builder setResult(int value) {
        result.hasResult = true;
        result.result_ = value;
        return this;
      }
      public Builder clearResult() {
        result.hasResult = false;
        result.result_ = 0;
        return this;
      }
      
      // optional int32 currentFloor = 2;
      public boolean hasCurrentFloor() {
        return result.hasCurrentFloor();
      }
      public int getCurrentFloor() {
        return result.getCurrentFloor();
      }
      public Builder setCurrentFloor(int value) {
        result.hasCurrentFloor = true;
        result.currentFloor_ = value;
        return this;
      }
      public Builder clearCurrentFloor() {
        result.hasCurrentFloor = false;
        result.currentFloor_ = 0;
        return this;
      }
    }
    
    static {
      com.chanyu.projectl.protobuf.Abyss.getDescriptor();
    }
    
    static {
      com.chanyu.projectl.protobuf.Abyss.internalForceInit();
    }
  }
  
  public static final class EndSecretPlaceFightRequestProto extends
      com.google.protobuf.GeneratedMessage {
    // Use EndSecretPlaceFightRequestProto.newBuilder() to construct.
    private EndSecretPlaceFightRequestProto() {}
    
    private static final EndSecretPlaceFightRequestProto defaultInstance = new EndSecretPlaceFightRequestProto();
    public static EndSecretPlaceFightRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public EndSecretPlaceFightRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chanyu.projectl.protobuf.Abyss.internal_static_chanyu_EndSecretPlaceFightRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chanyu.projectl.protobuf.Abyss.internal_static_chanyu_EndSecretPlaceFightRequestProto_fieldAccessorTable;
    }
    
    // required int32 currentFloor = 1;
    public static final int CURRENTFLOOR_FIELD_NUMBER = 1;
    private boolean hasCurrentFloor;
    private int currentFloor_ = 0;
    public boolean hasCurrentFloor() { return hasCurrentFloor; }
    public int getCurrentFloor() { return currentFloor_; }
    
    // required int32 battleResult = 2;
    public static final int BATTLERESULT_FIELD_NUMBER = 2;
    private boolean hasBattleResult;
    private int battleResult_ = 0;
    public boolean hasBattleResult() { return hasBattleResult; }
    public int getBattleResult() { return battleResult_; }
    
    public final boolean isInitialized() {
      if (!hasCurrentFloor) return false;
      if (!hasBattleResult) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCurrentFloor()) {
        output.writeInt32(1, getCurrentFloor());
      }
      if (hasBattleResult()) {
        output.writeInt32(2, getBattleResult());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCurrentFloor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCurrentFloor());
      }
      if (hasBattleResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getBattleResult());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto result;
      
      // Construct using com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto();
        return builder;
      }
      
      protected com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto.getDescriptor();
      }
      
      public com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto getDefaultInstanceForType() {
        return com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto) {
          return mergeFrom((com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto other) {
        if (other == com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto.getDefaultInstance()) return this;
        if (other.hasCurrentFloor()) {
          setCurrentFloor(other.getCurrentFloor());
        }
        if (other.hasBattleResult()) {
          setBattleResult(other.getBattleResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCurrentFloor(input.readInt32());
              break;
            }
            case 16: {
              setBattleResult(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 currentFloor = 1;
      public boolean hasCurrentFloor() {
        return result.hasCurrentFloor();
      }
      public int getCurrentFloor() {
        return result.getCurrentFloor();
      }
      public Builder setCurrentFloor(int value) {
        result.hasCurrentFloor = true;
        result.currentFloor_ = value;
        return this;
      }
      public Builder clearCurrentFloor() {
        result.hasCurrentFloor = false;
        result.currentFloor_ = 0;
        return this;
      }
      
      // required int32 battleResult = 2;
      public boolean hasBattleResult() {
        return result.hasBattleResult();
      }
      public int getBattleResult() {
        return result.getBattleResult();
      }
      public Builder setBattleResult(int value) {
        result.hasBattleResult = true;
        result.battleResult_ = value;
        return this;
      }
      public Builder clearBattleResult() {
        result.hasBattleResult = false;
        result.battleResult_ = 0;
        return this;
      }
    }
    
    static {
      com.chanyu.projectl.protobuf.Abyss.getDescriptor();
    }
    
    static {
      com.chanyu.projectl.protobuf.Abyss.internalForceInit();
    }
  }
  
  public static final class EndSecretPlaceFightResponseProto extends
      com.google.protobuf.GeneratedMessage {
    // Use EndSecretPlaceFightResponseProto.newBuilder() to construct.
    private EndSecretPlaceFightResponseProto() {}
    
    private static final EndSecretPlaceFightResponseProto defaultInstance = new EndSecretPlaceFightResponseProto();
    public static EndSecretPlaceFightResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public EndSecretPlaceFightResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chanyu.projectl.protobuf.Abyss.internal_static_chanyu_EndSecretPlaceFightResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chanyu.projectl.protobuf.Abyss.internal_static_chanyu_EndSecretPlaceFightResponseProto_fieldAccessorTable;
    }
    
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean hasResult;
    private int result_ = 0;
    public boolean hasResult() { return hasResult; }
    public int getResult() { return result_; }
    
    // optional int32 nextFloor = 2;
    public static final int NEXTFLOOR_FIELD_NUMBER = 2;
    private boolean hasNextFloor;
    private int nextFloor_ = 0;
    public boolean hasNextFloor() { return hasNextFloor; }
    public int getNextFloor() { return nextFloor_; }
    
    // optional double lastChallengeEndTime = 3;
    public static final int LASTCHALLENGEENDTIME_FIELD_NUMBER = 3;
    private boolean hasLastChallengeEndTime;
    private double lastChallengeEndTime_ = 0D;
    public boolean hasLastChallengeEndTime() { return hasLastChallengeEndTime; }
    public double getLastChallengeEndTime() { return lastChallengeEndTime_; }
    
    // repeated .chanyu.ItemProto items = 4;
    public static final int ITEMS_FIELD_NUMBER = 4;
    private java.util.List<com.chanyu.projectl.protobuf.ItemPackage.ItemProto> items_ =
      java.util.Collections.emptyList();
    public java.util.List<com.chanyu.projectl.protobuf.ItemPackage.ItemProto> getItemsList() {
      return items_;
    }
    public int getItemsCount() { return items_.size(); }
    public com.chanyu.projectl.protobuf.ItemPackage.ItemProto getItems(int index) {
      return items_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasResult) return false;
      for (com.chanyu.projectl.protobuf.ItemPackage.ItemProto element : getItemsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasResult()) {
        output.writeInt32(1, getResult());
      }
      if (hasNextFloor()) {
        output.writeInt32(2, getNextFloor());
      }
      if (hasLastChallengeEndTime()) {
        output.writeDouble(3, getLastChallengeEndTime());
      }
      for (com.chanyu.projectl.protobuf.ItemPackage.ItemProto element : getItemsList()) {
        output.writeMessage(4, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getResult());
      }
      if (hasNextFloor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getNextFloor());
      }
      if (hasLastChallengeEndTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, getLastChallengeEndTime());
      }
      for (com.chanyu.projectl.protobuf.ItemPackage.ItemProto element : getItemsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto result;
      
      // Construct using com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto();
        return builder;
      }
      
      protected com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto.getDescriptor();
      }
      
      public com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto getDefaultInstanceForType() {
        return com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.items_ != java.util.Collections.EMPTY_LIST) {
          result.items_ =
            java.util.Collections.unmodifiableList(result.items_);
        }
        com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto) {
          return mergeFrom((com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto other) {
        if (other == com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasNextFloor()) {
          setNextFloor(other.getNextFloor());
        }
        if (other.hasLastChallengeEndTime()) {
          setLastChallengeEndTime(other.getLastChallengeEndTime());
        }
        if (!other.items_.isEmpty()) {
          if (result.items_.isEmpty()) {
            result.items_ = new java.util.ArrayList<com.chanyu.projectl.protobuf.ItemPackage.ItemProto>();
          }
          result.items_.addAll(other.items_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setResult(input.readInt32());
              break;
            }
            case 16: {
              setNextFloor(input.readInt32());
              break;
            }
            case 25: {
              setLastChallengeEndTime(input.readDouble());
              break;
            }
            case 34: {
              com.chanyu.projectl.protobuf.ItemPackage.ItemProto.Builder subBuilder = com.chanyu.projectl.protobuf.ItemPackage.ItemProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addItems(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 result = 1;
      public boolean hasResult() {
        return result.hasResult();
      }
      public int getResult() {
        return result.getResult();
      }
      public Builder setResult(int value) {
        result.hasResult = true;
        result.result_ = value;
        return this;
      }
      public Builder clearResult() {
        result.hasResult = false;
        result.result_ = 0;
        return this;
      }
      
      // optional int32 nextFloor = 2;
      public boolean hasNextFloor() {
        return result.hasNextFloor();
      }
      public int getNextFloor() {
        return result.getNextFloor();
      }
      public Builder setNextFloor(int value) {
        result.hasNextFloor = true;
        result.nextFloor_ = value;
        return this;
      }
      public Builder clearNextFloor() {
        result.hasNextFloor = false;
        result.nextFloor_ = 0;
        return this;
      }
      
      // optional double lastChallengeEndTime = 3;
      public boolean hasLastChallengeEndTime() {
        return result.hasLastChallengeEndTime();
      }
      public double getLastChallengeEndTime() {
        return result.getLastChallengeEndTime();
      }
      public Builder setLastChallengeEndTime(double value) {
        result.hasLastChallengeEndTime = true;
        result.lastChallengeEndTime_ = value;
        return this;
      }
      public Builder clearLastChallengeEndTime() {
        result.hasLastChallengeEndTime = false;
        result.lastChallengeEndTime_ = 0D;
        return this;
      }
      
      // repeated .chanyu.ItemProto items = 4;
      public java.util.List<com.chanyu.projectl.protobuf.ItemPackage.ItemProto> getItemsList() {
        return java.util.Collections.unmodifiableList(result.items_);
      }
      public int getItemsCount() {
        return result.getItemsCount();
      }
      public com.chanyu.projectl.protobuf.ItemPackage.ItemProto getItems(int index) {
        return result.getItems(index);
      }
      public Builder setItems(int index, com.chanyu.projectl.protobuf.ItemPackage.ItemProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.items_.set(index, value);
        return this;
      }
      public Builder setItems(int index, com.chanyu.projectl.protobuf.ItemPackage.ItemProto.Builder builderForValue) {
        result.items_.set(index, builderForValue.build());
        return this;
      }
      public Builder addItems(com.chanyu.projectl.protobuf.ItemPackage.ItemProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.items_.isEmpty()) {
          result.items_ = new java.util.ArrayList<com.chanyu.projectl.protobuf.ItemPackage.ItemProto>();
        }
        result.items_.add(value);
        return this;
      }
      public Builder addItems(com.chanyu.projectl.protobuf.ItemPackage.ItemProto.Builder builderForValue) {
        if (result.items_.isEmpty()) {
          result.items_ = new java.util.ArrayList<com.chanyu.projectl.protobuf.ItemPackage.ItemProto>();
        }
        result.items_.add(builderForValue.build());
        return this;
      }
      public Builder addAllItems(
          java.lang.Iterable<? extends com.chanyu.projectl.protobuf.ItemPackage.ItemProto> values) {
        if (result.items_.isEmpty()) {
          result.items_ = new java.util.ArrayList<com.chanyu.projectl.protobuf.ItemPackage.ItemProto>();
        }
        super.addAll(values, result.items_);
        return this;
      }
      public Builder clearItems() {
        result.items_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      com.chanyu.projectl.protobuf.Abyss.getDescriptor();
    }
    
    static {
      com.chanyu.projectl.protobuf.Abyss.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chanyu_BeginSecretPlaceFightRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chanyu_BeginSecretPlaceFightRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chanyu_BeginSecretPlaceFightResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chanyu_BeginSecretPlaceFightResponseProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chanyu_EndSecretPlaceFightRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chanyu_EndSecretPlaceFightRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chanyu_EndSecretPlaceFightResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chanyu_EndSecretPlaceFightResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Abyss.proto\022\006chanyu\032\021ItemPackage.proto" +
      "\"J\n!BeginSecretPlaceFightRequestProto\022\024\n" +
      "\014currentFloor\030\001 \002(\005\022\017\n\007clearCD\030\002 \002(\010\"J\n\"" +
      "BeginSecretPlaceFightResponseProto\022\016\n\006re" +
      "sult\030\001 \002(\005\022\024\n\014currentFloor\030\002 \001(\005\"M\n\037EndS" +
      "ecretPlaceFightRequestProto\022\024\n\014currentFl" +
      "oor\030\001 \002(\005\022\024\n\014battleResult\030\002 \002(\005\"\205\001\n EndS" +
      "ecretPlaceFightResponseProto\022\016\n\006result\030\001" +
      " \002(\005\022\021\n\tnextFloor\030\002 \001(\005\022\034\n\024lastChallenge" +
      "EndTime\030\003 \001(\001\022 \n\005items\030\004 \003(\0132\021.chanyu.It",
      "emProtoB \n\034com.chanyu.projectl.protobufH" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_chanyu_BeginSecretPlaceFightRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_chanyu_BeginSecretPlaceFightRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chanyu_BeginSecretPlaceFightRequestProto_descriptor,
              new java.lang.String[] { "CurrentFloor", "ClearCD", },
              com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto.class,
              com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightRequestProto.Builder.class);
          internal_static_chanyu_BeginSecretPlaceFightResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_chanyu_BeginSecretPlaceFightResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chanyu_BeginSecretPlaceFightResponseProto_descriptor,
              new java.lang.String[] { "Result", "CurrentFloor", },
              com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto.class,
              com.chanyu.projectl.protobuf.Abyss.BeginSecretPlaceFightResponseProto.Builder.class);
          internal_static_chanyu_EndSecretPlaceFightRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_chanyu_EndSecretPlaceFightRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chanyu_EndSecretPlaceFightRequestProto_descriptor,
              new java.lang.String[] { "CurrentFloor", "BattleResult", },
              com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto.class,
              com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightRequestProto.Builder.class);
          internal_static_chanyu_EndSecretPlaceFightResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_chanyu_EndSecretPlaceFightResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chanyu_EndSecretPlaceFightResponseProto_descriptor,
              new java.lang.String[] { "Result", "NextFloor", "LastChallengeEndTime", "Items", },
              com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto.class,
              com.chanyu.projectl.protobuf.Abyss.EndSecretPlaceFightResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.chanyu.projectl.protobuf.ItemPackage.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
